const VERSION="0.0.3";
const NAME="AFO Mobile Visual Runtime";
const TOOLS=["create_design_system","create_scene_spec","create_premium_mobile_shell","compile_three_worker_page","compile_three_object_graph","compile_r3f_component_tree","compile_gltf_manifest","validate_mobile_performance_budget","generate_visual_receipt"];
const ROUTES=["/","/studio","/health","/llms.txt","/openapi.json","/agent-actions","/mcp/tools","/mcp/schema","/mcp/call","/api/sample-scene","/api/design/presets","/api/design/compile","/api/scene/export/three-json","/api/scene/export/r3f","/api/scene/export/gltf-manifest","/api/compile","/api/receipt"];
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const presets={themes:{black_glass_gold:{bg:"#03040a",a:"#ffd76b",b:"#74f7ff",panel:"rgba(8,10,20,.68)"},neon_space:{bg:"#00040a",a:"#00ffb2",b:"#66ccff",panel:"rgba(0,0,0,.62)"},pearl_future:{bg:"#eef6ff",a:"#405cff",b:"#00a3ff",panel:"rgba(255,255,255,.74)"}},layouts:["spherical_constellation","orbital_gallery","timeline_tunnel","project_showroom","data_cockpit"],huds:["luxury_cockpit","command_deck","bottom_sheet"],materials:["glass_cards_emissive_edges","hologram_nodes","matte_product_tiles"],lighting:["soft_studio_rim","neon_rim_key","museum_spotlight"],controls:["mobile_fly_with_snap_focus","orbit_drag_tap_select","dashboard_pan"]};
const sample={name:"Dogfoodma Premium Scene",theme:"black_glass_gold",layout:"spherical_constellation",hud:"luxury_cockpit",materials:"glass_cards_emissive_edges",lighting:"soft_studio_rim",controls:"mobile_fly_with_snap_focus",mobile:{pixelRatioCap:2,targetFps:45,lowPowerMode:true,maxObjects:180},data:{source:"inline",binding:"future:d1.projects+r2.assets",items:["Design System","Scene Compiler","R2 Textures","D1 Rows","MCP Tools","Visual Receipt"].map((title,i)=>({id:"node_"+i,title,cluster:i<2?"Dogfoodma":i<4?"Data":"Agents"}))}};
function J(v,s=200){return Response.json(v,{status:s,headers:CORS})}
function T(v,t="text/plain; charset=utf-8"){return new Response(v,{headers:{...CORS,"Content-Type":t,"Cache-Control":"no-store"}})}
function slug(v){return String(v||"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")||"black_glass_gold"}
function theme(n){return presets.themes[slug(n)]||presets.themes.black_glass_gold}
function norm(x={}){x=x&&typeof x==="object"?x:{};let d=x.data||{},m=x.mobile||{},items=Array.isArray(d.items)?d.items:Array.isArray(x.items)?x.items:sample.data.items,th=slug(x.theme||"black_glass_gold");return {name:String(x.name||"Untitled Premium Scene"),version:VERSION,theme:th,layout:String(x.layout||"spherical_constellation"),hud:String(x.hud||"luxury_cockpit"),materials:String(x.materials||"glass_cards_emissive_edges"),lighting:String(x.lighting||"soft_studio_rim"),controls:String(x.controls||"mobile_fly_with_snap_focus"),mobile:{pixelRatioCap:Number(m.pixelRatioCap||2),targetFps:Number(m.targetFps||45),lowPowerMode:m.lowPowerMode!==false,maxObjects:Number(m.maxObjects||180)},data:{source:String(d.source||"inline"),binding:String(d.binding||"inline"),items:items.map((it,i)=>typeof it==="string"?{id:"item_"+i,title:it,cluster:"Default"}:{id:String(it.id||"item_"+i),title:String(it.title||it.name||"Item "+i),cluster:String(it.cluster||"Default"),url:String(it.url||"")})}}}
function design(x){let s=norm(x),c=theme(s.theme);return {ok:true,tokens:{theme:s.theme,colors:{background:c.bg,accent:c.a,accent2:c.b,panel:c.panel},radius:{panel:24,button:999,card:28},motion:{ease:"cubic-bezier(.2,.9,.2,1)",durationMs:420},surfaces:{hud:s.hud,material:s.materials,lighting:s.lighting}}}}
function budget(s){let count=s.data.items.length,draw=Math.min(count+8,s.mobile.lowPowerMode?90:180);return {ok:draw<=120,profile:s.mobile.lowPowerMode?"phone-safe":"premium",estimatedObjects:count,estimatedDrawCalls:draw,pixelRatioCap:s.mobile.pixelRatioCap,targetFps:s.mobile.targetFps}}
function positions(s){let n=Math.max(1,s.data.items.length);return s.data.items.map((it,i)=>{let a=i/n*Math.PI*2;return {...it,x:Math.cos(a)*340,y:Math.sin(i*1.73)*95,z:Math.sin(a)*340}})}
function threeJson(x){let s=norm(x),c=theme(s.theme);return {metadata:{version:4.6,type:"Object",generator:NAME+" "+VERSION},object:{type:"Scene",name:s.name,background:c.bg,userData:{dogfoodma:s,budget:budget(s)},children:positions(s).map((n,i)=>({type:"Mesh",name:n.title,position:[n.x,n.y,n.z],userData:n,geometry:{type:"IcosahedronGeometry",radius:24},material:{type:"MeshStandardMaterial",color:i%2?c.b:c.a}}))}}}
function r3f(x){let s=norm(x),nodes=positions(s);return "function Scene(){ const nodes="+JSON.stringify(nodes)+"; return <Canvas>{nodes.map(n=><mesh key={n.id} position={[n.x,n.y,n.z]} />)}</Canvas> }"}
function gltf(x){let s=norm(x);return {asset:{version:"2.0",generator:NAME+" "+VERSION},scene:0,scenes:[{name:s.name,nodes:s.data.items.map((_,i)=>i)}],nodes:positions(s).map(n=>({name:n.title,translation:[n.x,n.y,n.z],extras:n}))}}
function receipt(x,source="runtime"){let s=norm(x);return {ok:true,runtime:NAME,version:VERSION,source,scene_id:"scene_"+Math.random().toString(36).slice(2),theme:s.theme,layout:s.layout,hud:s.hud,item_count:s.data.items.length,budget:budget(s),exports:["three-worker-inline","three-json","r3f","gltf-manifest"]}}
function page(x){let s=norm(x),c=theme(s.theme),items=positions(s);return `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>${s.name}</title><style>html,body{margin:0;height:100%;background:radial-gradient(circle at 25% 20%,${c.a}33,transparent 30%),radial-gradient(circle at 80% 70%,${c.b}33,transparent 34%),${c.bg};color:#fff;font-family:system-ui;overflow:hidden}.hud{position:fixed;inset:16px;display:grid;grid-template-rows:auto 1fr auto;pointer-events:none}.panel{background:${c.panel};border:1px solid ${c.a}77;border-radius:28px;padding:16px;backdrop-filter:blur(18px);box-shadow:0 30px 90px #0008}.k{color:${c.a};font:800 11px ui-monospace;letter-spacing:.16em;text-transform:uppercase}h1{margin:6px 0;font-size:24px}.chips{display:flex;gap:8px;flex-wrap:wrap}.chip{border:1px solid #fff2;border-radius:99px;padding:7px 10px;color:${c.b};font:800 10px ui-monospace}.space{position:absolute;inset:0}.node{position:absolute;left:50%;top:50%;width:72px;height:72px;margin:-36px;border-radius:24px;background:linear-gradient(135deg,${c.a},${c.b});box-shadow:0 0 44px ${c.a}88;display:grid;place-items:center;font-weight:900;transform:translate(var(--x),var(--y)) scale(var(--s));animation:float 5s ease-in-out infinite alternate}.node span{position:absolute;top:82px;white-space:nowrap;font-size:11px}.bottom{align-self:end;display:grid;grid-template-columns:1fr 1fr;gap:10px}.btn{background:${c.panel};border:1px solid ${c.a}77;border-radius:999px;color:white;padding:14px;text-align:center;font-weight:900}@keyframes float{to{translate:0 -18px}}</style><div class="space">${items.map((n,i)=>`<div class="node" style="--x:${Math.round(n.x/2)}px;--y:${Math.round(n.y*1.4)}px;--s:${1+(i%3)*.08};animation-delay:${i*.2}s">${i+1}<span>${n.title}</span></div>`).join("")}</div><div class="hud"><div class="panel"><div class="k">${s.layout} · ${s.hud}</div><h1>${s.name}</h1><div class="chips"><div class="chip">${s.theme}</div><div class="chip">${s.materials}</div><div class="chip">${s.controls}</div></div></div><div></div><div class="bottom"><div class="btn">Premium Shell</div><div class="btn">${s.data.items.length} Objects</div></div></div>`}
async function body(req){try{return await req.json()}catch{return null}}
async function mcp(p){let tool=p?.tool||p?.name,input=p?.input||{};if(tool==="create_design_system")return design(input);if(tool==="create_scene_spec")return {ok:true,spec:norm(input),budget:budget(norm(input))};if(tool==="create_premium_mobile_shell"||tool==="compile_three_worker_page")return {ok:true,html:page(input),receipt:receipt(input,"mcp")};if(tool==="compile_three_object_graph")return {ok:true,three_json:threeJson(input)};if(tool==="compile_r3f_component_tree")return {ok:true,tsx:r3f(input)};if(tool==="compile_gltf_manifest")return {ok:true,gltf:gltf(input)};if(tool==="validate_mobile_performance_budget")return {ok:true,budget:budget(norm(input))};if(tool==="generate_visual_receipt")return receipt(input,"mcp");return {ok:false,error:"unknown_tool",available:TOOLS}}
export default {async fetch(req){if(req.method==="OPTIONS")return new Response(null,{headers:CORS});let u=new URL(req.url),o=u.origin;if(u.pathname==="/"||u.pathname==="/studio"||u.pathname==="/preview")return T(page(sample),"text/html; charset=utf-8");if(u.pathname==="/health")return J({ok:true,name:NAME,version:VERSION,routes:ROUTES});if(u.pathname==="/llms.txt")return T(`# ${NAME}\n\nVersion: ${VERSION}\n\nPremium frontend MCP-style runtime. Use /mcp/tools, /mcp/schema, /api/design/presets, and /api/compile.`);if(u.pathname==="/openapi.json")return J({openapi:"3.1.0",info:{title:NAME,version:VERSION},servers:[{url:o}],paths:{"/mcp/call":{post:{operationId:"callTool"}},"/api/design/presets":{get:{operationId:"listDesignPresets"}},"/api/compile":{post:{operationId:"compileThreePage"}}}});if(u.pathname==="/agent-actions")return J({name:NAME,version:VERSION,base_url:o,actions:TOOLS.map(id=>({id,method:"POST",endpoint:o+"/mcp/call"}))});if(u.pathname==="/mcp/tools")return J({name:NAME,version:VERSION,tools:TOOLS.map(name=>({name,description:name+" for premium frontend generation"}))});if(u.pathname==="/mcp/schema")return J({name:NAME,version:VERSION,presets,sample,designSystem:design(sample).tokens,sceneSpec:norm(sample)});if(u.pathname==="/mcp/call"&&req.method==="POST")return J(await mcp(await body(req)));if(u.pathname==="/api/sample-scene")return J(sample);if(u.pathname==="/api/design/presets")return J({ok:true,version:VERSION,presets});if(u.pathname==="/api/design/compile"&&req.method==="POST")return J(design(await body(req)));if(u.pathname==="/api/scene/export/three-json"&&req.method==="POST")return J({ok:true,three_json:threeJson(await body(req))});if(u.pathname==="/api/scene/export/r3f"&&req.method==="POST")return J({ok:true,tsx:r3f(await body(req))});if(u.pathname==="/api/scene/export/gltf-manifest"&&req.method==="POST")return J({ok:true,gltf:gltf(await body(req))});if(u.pathname==="/api/compile"&&req.method==="POST")return J({ok:true,html:page(await body(req)),receipt:receipt(await body(req),"api")});if(u.pathname==="/api/receipt")return J(receipt(sample,"sample"));return J({ok:false,error:"not_found",routes:ROUTES},404)}};
